#!/usr/bin/env python3
"""
Fieldwork RSS Fetcher
=====================
Fetches citizen science stories from RSS feeds, assigns credibility labels,
and updates the site's articles data file.

Runs twice daily via GitHub Actions. Picks 3 stories per run (≈6/day).
"""

import json
import hashlib
import re
import sys
import os
from datetime import datetime, timezone
from urllib.request import urlopen, Request
from urllib.error import URLError
from xml.etree import ElementTree as ET

# ─── CONFIG ───
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SOURCES_FILE = os.path.join(SCRIPT_DIR, "sources.json")
DATA_DIR = os.path.join(SCRIPT_DIR, "..", "data")
ARTICLES_JSON = os.path.join(DATA_DIR, "articles.json")
ARTICLES_JS = os.path.join(DATA_DIR, "articles.js")
SEEN_FILE = os.path.join(DATA_DIR, "seen.json")

USER_AGENT = "Fieldwork-RSS-Bot/1.0 (citizen science news aggregator)"


def load_config():
    with open(SOURCES_FILE, "r") as f:
        return json.load(f)


def load_seen():
    """Load set of already-seen article hashes to avoid duplicates."""
    if os.path.exists(SEEN_FILE):
        with open(SEEN_FILE, "r") as f:
            return set(json.load(f))
    return set()


def save_seen(seen):
    # Keep only last 5000 entries to prevent unbounded growth
    seen_list = list(seen)[-5000:]
    with open(SEEN_FILE, "w") as f:
        json.dump(seen_list, f)


def load_articles():
    if os.path.exists(ARTICLES_JSON):
        with open(ARTICLES_JSON, "r") as f:
            return json.load(f)
    return []


def save_articles(articles, max_articles):
    """Save articles to both JSON (for script) and JS (for site)."""
    # Trim to max
    articles = articles[:max_articles]

    # Reassign IDs sequentially
    for i, article in enumerate(articles):
        article["id"] = i + 1

    # Save JSON
    with open(ARTICLES_JSON, "w") as f:
        json.dump(articles, f, indent=2, ensure_ascii=False)

    # Generate JS file
    js_header = """/*
 * Fieldwork — Articles Database
 * Auto-generated by RSS fetcher. Do not edit directly.
 * Last updated: {timestamp}
 *
 * To manually add a story, add it to articles.json and run the fetcher,
 * or edit this file directly following the format below.
 */

const articles = """.format(timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))

    js_footer = """;

export default articles;
"""

    with open(ARTICLES_JS, "w") as f:
        f.write(js_header)
        f.write(json.dumps(articles, indent=2, ensure_ascii=False))
        f.write(js_footer)


def article_hash(title, source):
    """Create a unique hash for deduplication."""
    key = f"{title.lower().strip()}|{source.lower().strip()}"
    return hashlib.md5(key.encode()).hexdigest()[:12]


def clean_html(text):
    """Strip HTML tags and clean up text."""
    if not text:
        return ""
    # Remove HTML tags
    text = re.sub(r"<[^>]+>", "", text)
    # Remove CDATA
    text = re.sub(r"<!\[CDATA\[|\]\]>", "", text)
    # Decode common entities
    text = text.replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
    text = text.replace("&quot;", '"').replace("&#39;", "'").replace("&apos;", "'")
    # Clean whitespace
    text = re.sub(r"\s+", " ", text).strip()
    return text


def truncate(text, max_len):
    if len(text) <= max_len:
        return text
    # Cut at last space before max_len
    truncated = text[:max_len].rsplit(" ", 1)[0]
    return truncated.rstrip(".,;:!?") + "..."


def fetch_feed(url):
    """Fetch and parse an RSS/Atom feed."""
    try:
        req = Request(url, headers={"User-Agent": USER_AGENT})
        with urlopen(req, timeout=15) as resp:
            content = resp.read()
        return ET.fromstring(content)
    except (URLError, ET.ParseError, Exception) as e:
        print(f"  ⚠ Failed to fetch {url}: {e}")
        return None


def parse_entries(root):
    """Parse RSS or Atom feed entries."""
    entries = []
    ns = {"atom": "http://www.w3.org/2005/Atom", "dc": "http://purl.org/dc/elements/1.1/"}

    # Try RSS 2.0 first
    for item in root.findall(".//item"):
        title = item.findtext("title", "")
        link = item.findtext("link", "")
        desc = item.findtext("description", "")
        pub_date = item.findtext("pubDate", "")
        entries.append({
            "title": clean_html(title),
            "link": link.strip() if link else "",
            "description": clean_html(desc),
            "pub_date": pub_date,
        })

    # Try Atom
    if not entries:
        for entry in root.findall("atom:entry", ns):
            title = entry.findtext("atom:title", "", ns)
            link_el = entry.find("atom:link[@rel='alternate']", ns)
            if link_el is None:
                link_el = entry.find("atom:link", ns)
            link = link_el.get("href", "") if link_el is not None else ""
            summary = entry.findtext("atom:summary", "", ns)
            content = entry.findtext("atom:content", "", ns)
            pub_date = entry.findtext("atom:published", "", ns) or entry.findtext("atom:updated", "", ns)
            entries.append({
                "title": clean_html(title),
                "link": link.strip(),
                "description": clean_html(summary or content),
                "pub_date": pub_date,
            })

    return entries


def matches_keywords(title, description, keywords, threshold):
    """Check if an article matches citizen science keywords."""
    text = f"{title} {description}".lower()

    # Any primary keyword = instant match
    for kw in keywords["primary"]:
        if kw.lower() in text:
            return True

    # Need threshold secondary keywords
    count = sum(1 for kw in keywords["secondary"] if kw.lower() in text)
    return count >= threshold


def calculate_hours_ago(pub_date_str):
    """Estimate hours since publication."""
    if not pub_date_str:
        return 6  # Default
    try:
        # Try common RSS date formats
        for fmt in [
            "%a, %d %b %Y %H:%M:%S %z",
            "%a, %d %b %Y %H:%M:%S %Z",
            "%Y-%m-%dT%H:%M:%S%z",
            "%Y-%m-%dT%H:%M:%SZ",
            "%Y-%m-%d %H:%M:%S",
        ]:
            try:
                dt = datetime.strptime(pub_date_str.strip(), fmt)
                if dt.tzinfo is None:
                    dt = dt.replace(tzinfo=timezone.utc)
                delta = datetime.now(timezone.utc) - dt
                hours = max(1, int(delta.total_seconds() / 3600))
                return min(hours, 720)  # Cap at 30 days
            except ValueError:
                continue
    except Exception:
        pass
    return 6  # Default fallback


def determine_trending(title, description):
    """Simple heuristic for trending — boost stories with strong signals."""
    text = f"{title} {description}".lower()
    hot_words = ["breakthrough", "first ever", "discovered", "unprecedented",
                 "new species", "record-breaking", "award", "million",
                 "groundbreaking", "landmark", "historic"]
    score = sum(30 for w in hot_words if w in text)
    score += len(description) // 50  # Longer = more substance
    return score > 50, min(score + 100, 999)


def main():
    print("🌱 Fieldwork RSS Fetcher")
    print("=" * 50)

    config = load_config()
    settings = config["settings"]
    keywords = config["keywords"]
    sources = config["sources"]
    seen = load_seen()
    articles = load_articles()

    stories_needed = settings["stories_per_run"]
    new_stories = []

    # Shuffle sources to vary which ones we pull from
    import random
    random.shuffle(sources)

    for source in sources:
        if len(new_stories) >= stories_needed:
            break

        print(f"\n📡 Fetching: {source['name']}")
        root = fetch_feed(source["url"])
        if root is None:
            continue

        entries = parse_entries(root)
        print(f"   Found {len(entries)} entries")

        for entry in entries:
            if len(new_stories) >= stories_needed:
                break

            if not entry["title"] or not entry["description"]:
                continue

            # Check if already seen
            h = article_hash(entry["title"], source["name"])
            if h in seen:
                continue

            # Keyword filter (if source needs it)
            if source["needs_keyword_filter"]:
                if not matches_keywords(entry["title"], entry["description"], keywords, settings["keyword_match_threshold"]):
                    continue

            # Build article
            trending, trend_score = determine_trending(entry["title"], entry["description"])
            hours_ago = calculate_hours_ago(entry["pub_date"])

            article = {
                "id": 0,  # Will be reassigned
                "title": entry["title"],
                "source": source["name"],
                "category": source["category"],
                "hoursAgo": hours_ago,
                "excerpt": truncate(entry["description"], settings["max_excerpt_length"]),
                "credibility": source["credibility"],
                "type": source["type"],
                "featured": False,
                "readTime": f"{max(2, len(entry['description'].split()) // 40)} min",
                "trending": trending,
                "trendScore": trend_score,
                "sourceUrl": entry["link"],
            }

            new_stories.append(article)
            seen.add(h)
            print(f"   ✅ {entry['title'][:70]}...")

    if not new_stories:
        print("\n⚠ No new stories found this run.")
        save_seen(seen)
        return

    # Mark the best new story as featured (if it's trending)
    best = max(new_stories, key=lambda s: s["trendScore"])
    if best["trending"]:
        best["featured"] = True

    # Prepend new stories to existing
    articles = new_stories + articles

    # Unfeature old featured stories (keep max 2 featured)
    featured_count = 0
    for a in articles:
        if a["featured"]:
            featured_count += 1
            if featured_count > 2:
                a["featured"] = False

    # Save everything
    save_articles(articles, settings["max_articles_on_site"])
    save_seen(seen)

    print(f"\n🎉 Added {len(new_stories)} new stories!")
    for s in new_stories:
        print(f"   • [{s['category']}] {s['title'][:60]}...")
    print(f"\n📊 Total stories on site: {min(len(articles), settings['max_articles_on_site'])}")


if __name__ == "__main__":
    main()
